# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'machine_learning.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QWidget, QFileDialog, QPushButton, QLabel, QVBoxLayout, QLineEdit)
from PyQt5.QtGui import QPixmap,QImage
from PyQt5.QtCore import QDir
from PyQt5.QtCore import QProcess
# import numpy as np  
from subprocess import call



class Ui_machineWindow(object):

    def send_dataset(self, machine_test):

        year =self.comboBox_year.currentText()
        with open('year.txt', 'w') as f:
            if (year == "2007"):
                f.write("0")
            elif (year == "2008"):
                f.write("1")
            else:
                f.write("2")
        
        month = self.comboBox_month.currentText()
        m = {"January" : "1",
            "February" : "2",
            "March" : "3",
            "April" : "4",
            "May" : "5",
            "June" : "6",
            "July" : "7",
            "August" : "8",
            "September" : "9",
            "October" : "10",
            "November" : "11",
            "December" : "12", 
            }
        with open('month.txt', 'w') as f:
            for key in m:
                if key == month:
                    f.write(m[key])
                    break

        season = self.comboBox_season.currentText()
        with open('season.txt', 'w') as f:
            if (season == "Dry"):
                f.write("0")
            else:
                f.write("1")
    
        province = self.comboBox_province.currentText()
        with open('province.txt', 'w') as f:
            f.write("0")
    
        town = self.comboBox_municipality.currentText()
        with open('town.txt', 'w') as f:
            if (town == "Bay"):
                f.write("0")
            elif (town == "Biñan"):
                f.write("1")
            elif (town == "Cabuyao"):
                f.write("2")
            elif (town == "Calamba"):
                f.write("3")
            elif (town == "Calauan"):
                f.write("4")
            else:
                f.write("5")
            
        size = self.lineEdit_size.text()
        with open('size.txt', 'w') as f:
            f.write(size)
            
        tmax = self.tmaxEdit.text()
        with open('tmax.txt', 'w') as f:
            f.write(tmax)
            
        tmin = self.tminEdit.text()
        with open('tmin.txt', 'w') as f:
            f.write(tmin)
        
        thum = self.thumEdit.text()
        with open('thum.txt', 'w') as f:
            f.write(thum)

        phos = self.phos_textEdit.text()
        with open('phos.txt', 'w') as f:
            f.write(phos)
        
        nit = self.nitrogen_textEdit_2.text()
        with open('nit.txt', 'w') as f:
            f.write(nit)

        pot = self.pot_textEdit.text()
        with open('pot.txt', 'w') as f:
            f.write(pot)
        
        irrigation = self.comboBox_irrigation.currentText()
        with open('irrigation.txt', 'w') as f:
            if (irrigation == "Gravity"):
                f.write("0")
            elif (irrigation =="Pump"):
                f.write("1")
            else:
                f.write("2")
        
        import yield_analysis_v4
        # machineWindow.close()

        

    def setupUi(self, machineWindow):
        machineWindow.setObjectName("machineWindow")
        machineWindow.resize(900, 600)
        machineWindow.setMinimumSize(QtCore.QSize(900, 600))
        machineWindow.setMaximumSize(QtCore.QSize(900, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        machineWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(machineWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.label.setMinimumSize(QtCore.QSize(900, 600))
        self.label.setMaximumSize(QtCore.QSize(900, 600))
        self.label.setStyleSheet("background-color: rgb(211, 217, 97);\n"
"background-image: url(:/newPrefix/machine learning bg.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.comboBox_year = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_year.setGeometry(QtCore.QRect(120, 280, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_year.setFont(font)
        self.comboBox_year.setObjectName("comboBox_year")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_year.addItem("")
        self.comboBox_month = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_month.setGeometry(QtCore.QRect(120, 340, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_month.setFont(font)
        self.comboBox_month.setObjectName("comboBox_month")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_month.addItem("")
        self.comboBox_season = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_season.setGeometry(QtCore.QRect(120, 400, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_season.setFont(font)
        self.comboBox_season.setObjectName("comboBox_season")
        self.comboBox_season.addItem("")
        self.comboBox_season.addItem("")
        self.comboBox_irrigation = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_irrigation.setGeometry(QtCore.QRect(120, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_irrigation.setFont(font)
        self.comboBox_irrigation.setObjectName("comboBox_irrigation")
        self.comboBox_irrigation.addItem("")
        self.comboBox_irrigation.addItem("")
        self.comboBox_irrigation.addItem("")
        self.comboBox_municipality = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_municipality.setGeometry(QtCore.QRect(120, 520, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_municipality.setFont(font)
        self.comboBox_municipality.setObjectName("comboBox_municipality")
        self.comboBox_municipality.addItem("")
        self.comboBox_municipality.addItem("")
        self.comboBox_municipality.addItem("")
        self.comboBox_municipality.addItem("")
        self.comboBox_municipality.addItem("")
        self.comboBox_municipality.addItem("")
        self.comboBox_province = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_province.setGeometry(QtCore.QRect(370, 280, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_province.setFont(font)
        self.comboBox_province.setObjectName("comboBox_province")
        self.comboBox_province.addItem("")
        self.tmaxEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tmaxEdit.setGeometry(QtCore.QRect(370, 340, 131, 31))
        self.tmaxEdit.setObjectName("tmaxEdit")
        self.tminEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tminEdit.setGeometry(QtCore.QRect(370, 400, 131, 31))
        self.tminEdit.setObjectName("tminEdit")
        self.thumEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.thumEdit.setGeometry(QtCore.QRect(370, 460, 131, 31))
        self.thumEdit.setObjectName("thumEdit")
        self.nitrogen_textEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.nitrogen_textEdit_2.setGeometry(QtCore.QRect(370, 520, 131, 31))
        self.nitrogen_textEdit_2.setObjectName("nitrogen_textEdit_2")
        self.phos_textEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.phos_textEdit.setGeometry(QtCore.QRect(620, 280, 131, 31))
        self.phos_textEdit.setObjectName("phos_textEdit")
        self.pot_textEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pot_textEdit.setGeometry(QtCore.QRect(620, 340, 131, 31))
        self.pot_textEdit.setObjectName("pot_textEdit")
        self.lineEdit_size = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_size.setGeometry(QtCore.QRect(620, 400, 131, 31))
        self.lineEdit_size.setObjectName("lineEdit_size")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(76, 285, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(66, 345, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 406, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 465, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(36, 525, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(306, 286, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(283, 344, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(289, 405, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(274, 465, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(306, 524, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(533, 285, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(542, 345, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(540, 405, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.send_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_data_button.setGeometry(QtCore.QRect(540, 470, 281, 81))
        self.send_data_button.clicked.connect(self.send_dataset)
        self.send_data_button.setStyleSheet("QPushButton {\n"
"    image: url(:/newPrefix/proceed.png);\n"
"    background-color: rgb(166, 197, 103);\n"
"    border-width: 2px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    image: url(:/newPrefix/proceed.png);\n"
"    background-color: rgb(176, 197, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    image: url(:/newPrefix/proceed.png);\n"
"    background-color: rgb(151, 197, 76);\n"
"}\n"
"\n"
"\n"
"")
        self.send_data_button.setText("")
        self.send_data_button.setObjectName("send_data_button")
        machineWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(machineWindow)
        QtCore.QMetaObject.connectSlotsByName(machineWindow)

    def retranslateUi(self, machineWindow):
        _translate = QtCore.QCoreApplication.translate
        machineWindow.setWindowTitle(_translate("machineWindow", "Rice Criop Yield Prediction"))
        self.comboBox_year.setItemText(0, _translate("machineWindow", "2007"))
        self.comboBox_year.setItemText(1, _translate("machineWindow", "2008"))
        self.comboBox_year.setItemText(2, _translate("machineWindow", "2009"))
        self.comboBox_year.setItemText(3, _translate("machineWindow", "2010"))
        self.comboBox_year.setItemText(4, _translate("machineWindow", "2011"))
        self.comboBox_year.setItemText(5, _translate("machineWindow", "2012"))
        self.comboBox_year.setItemText(6, _translate("machineWindow", "2013"))
        self.comboBox_year.setItemText(7, _translate("machineWindow", "2014"))
        self.comboBox_year.setItemText(8, _translate("machineWindow", "2015"))
        self.comboBox_year.setItemText(9, _translate("machineWindow", "2016"))
        self.comboBox_year.setItemText(10, _translate("machineWindow", "2017"))
        self.comboBox_year.setItemText(11, _translate("machineWindow", "2018"))
        self.comboBox_year.setItemText(12, _translate("machineWindow", "2019"))
        self.comboBox_year.setItemText(13, _translate("machineWindow", "2020"))
        self.comboBox_year.setItemText(14, _translate("machineWindow", "2021"))
        self.comboBox_month.setItemText(0, _translate("machineWindow", "January"))
        self.comboBox_month.setItemText(1, _translate("machineWindow", "February"))
        self.comboBox_month.setItemText(2, _translate("machineWindow", "March"))
        self.comboBox_month.setItemText(3, _translate("machineWindow", "April"))
        self.comboBox_month.setItemText(4, _translate("machineWindow", "May"))
        self.comboBox_month.setItemText(5, _translate("machineWindow", "June"))
        self.comboBox_month.setItemText(6, _translate("machineWindow", "July"))
        self.comboBox_month.setItemText(7, _translate("machineWindow", "August"))
        self.comboBox_month.setItemText(8, _translate("machineWindow", "September"))
        self.comboBox_month.setItemText(9, _translate("machineWindow", "October"))
        self.comboBox_month.setItemText(10, _translate("machineWindow", "November"))
        self.comboBox_month.setItemText(11, _translate("machineWindow", "December"))
        self.comboBox_season.setItemText(0, _translate("machineWindow", "Wet"))
        self.comboBox_season.setItemText(1, _translate("machineWindow", "Dry"))
        self.comboBox_irrigation.setItemText(0, _translate("machineWindow", "Gravity"))
        self.comboBox_irrigation.setItemText(1, _translate("machineWindow", "Rainfed"))
        self.comboBox_irrigation.setItemText(2, _translate("machineWindow", "Pump"))
        self.comboBox_municipality.setItemText(0, _translate("machineWindow", "Bay"))
        self.comboBox_municipality.setItemText(1, _translate("machineWindow", "Biñan"))
        self.comboBox_municipality.setItemText(2, _translate("machineWindow", "Cabuyao"))
        self.comboBox_municipality.setItemText(3, _translate("machineWindow", "Calamba"))
        self.comboBox_municipality.setItemText(4, _translate("machineWindow", "Calauan"))
        self.comboBox_municipality.setItemText(5, _translate("machineWindow", "Sta. Rosa"))
        self.comboBox_province.setItemText(0, _translate("machineWindow", "Laguna"))
        self.label_2.setText(_translate("machineWindow", "Year:"))
        self.label_3.setText(_translate("machineWindow", "Month:"))
        self.label_4.setText(_translate("machineWindow", "Season:"))
        self.label_5.setText(_translate("machineWindow", "Irrigation:"))
        self.label_6.setText(_translate("machineWindow", "Municipality:"))
        self.label_7.setText(_translate("machineWindow", "Province:"))
        self.label_8.setText(_translate("machineWindow", "Max Temp.:"))
        self.label_9.setText(_translate("machineWindow", "Min Temp.:"))
        self.label_10.setText(_translate("machineWindow", "Avg Humidity:"))
        self.label_11.setText(_translate("machineWindow", "Nitrogen:"))
        self.label_12.setText(_translate("machineWindow", "Phosphorus:"))
        self.label_13.setText(_translate("machineWindow", "Potassium:"))
        self.label_14.setText(_translate("machineWindow", "Total Area:"))
from machine_learning_folder import bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    machineWindow = QtWidgets.QMainWindow()
    ui = Ui_machineWindow()
    ui.setupUi(machineWindow)
    machineWindow.show()
    sys.exit(app.exec_())
