# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ndvi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QWidget, QFileDialog, QPushButton, QLabel, QVBoxLayout, QLineEdit)
from PyQt5.QtGui import QPixmap,QImage
from PyQt5.QtCore import QDir
from PyQt5.QtCore import QProcess
# import numpy as np  
from subprocess import call


class Ui_improcessWindow(object):

    def proceed(self, improcesswindow):  # "calculate" button
        import ndviandendviandsavibatchversion
        
    def uploadphoto(self, imageprocessing_window): # "upload a file" button
        filename = QFileDialog.getExistingDirectory()
        self.textEdit.setText(filename)
        with open('improcess_path.txt', 'w') as f:
            f.write(filename)
        return filename

    def setupUi(self, improcessWindow):
        improcessWindow.setObjectName("improcessWindow")
        improcessWindow.resize(900, 600)
        improcessWindow.setMinimumSize(QtCore.QSize(900, 600))
        improcessWindow.setMaximumSize(QtCore.QSize(900, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        improcessWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(improcessWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 900, 600))
        self.label.setMinimumSize(QtCore.QSize(900, 600))
        self.label.setStyleSheet("background-color: rgb(211, 217, 97);\n"
"background-image: url(:/newPrefix/ndvi bg.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(80, 390, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.proceedButton = QtWidgets.QPushButton(self.centralwidget)
        self.proceedButton.setGeometry(QtCore.QRect(180, 460, 281, 81))
        self.proceedButton.clicked.connect(self.proceed)
        self.proceedButton.setStyleSheet("QPushButton {\n"
"    image: url(:/newPrefix/proceed.png);\n"
"    background-color: rgb(166, 197, 103);\n"
"    border-width: 2px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    image: url(:/newPrefix/proceed.png);\n"
"    background-color: rgb(176, 197, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    image: url(:/newPrefix/proceed.png);\n"
"    background-color: rgb(151, 197, 76);\n"
"}\n"
"\n"
"\n"
"")
        self.proceedButton.setText("")
        self.proceedButton.setObjectName("proceedButton")
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.clicked.connect(self.uploadphoto)
        self.uploadButton.setGeometry(QtCore.QRect(570, 350, 250, 200))
        self.uploadButton.setStyleSheet("QPushButton {\n"
"    image: url(:/newPrefix/upload.png);\n"
"    background-color: rgb(166, 197, 103);\n"
"    border-width: 2px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    image: url(:/newPrefix/upload.png);\n"
"    background-color: rgb(176, 197, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    image: url(:/newPrefix/upload.png);\n"
"    background-color: rgb(151, 197, 76);\n"
"}\n"
"\n"
"\n"
"")
        self.uploadButton.setText("")
        self.uploadButton.setObjectName("uploadButton")
        improcessWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(improcessWindow)
        self.statusBar.setObjectName("statusBar")
        improcessWindow.setStatusBar(self.statusBar)

        self.retranslateUi(improcessWindow)
        QtCore.QMetaObject.connectSlotsByName(improcessWindow)

    def retranslateUi(self, improcessWindow):
        _translate = QtCore.QCoreApplication.translate
        improcessWindow.setWindowTitle(_translate("improcessWindow", "NDVI Calculation"))
from image_process import bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    improcessWindow = QtWidgets.QMainWindow()
    ui = Ui_improcessWindow()
    ui.setupUi(improcessWindow)
    improcessWindow.show()
    sys.exit(app.exec_())
